# run: conda env create -f environment.yml
name: nerf_rl
channels:
  - pytorch
  - pytorch3d
  - defaults
  - nvidia
  - fvcore
  - iopath
  - conda-forge
  - bottler
dependencies:
  - python>=3.8
  - pip
  - pip:
      - pyhocon
      - plotly
      - opencv-python
      - dotmap
      - tensorboard
      - imageio
      - imageio-ffmpeg
      - ipdb
      - pretrainedmodels
      - lpips
      - tensorflow
      - wandb
      - hydra-core
      - omegaconf
      - pytorch-lightning
      - pybullet
      - moviepy
      - imageio
  
  - scipy
  - numpy
  - matplotlib
  - pytorch #==1.6.0
  - torchvision #==0.7.0
  - scikit-image #==0.17.2
  - pytorch-cuda==11.6
  - tqdm
  - fvcore
  - iopath
  - nvidiacub
  - jupyter
  - pytorch3d