model:
  target: src.model.vanilla_bc_rw.Vanilla_BC_RW

  params:
    ckpt_path: /work/dlclarge2/faridk-nerf_il/logs/bc_rw/2023-03-15T14-35-07_rw_bc_vanilla_augment_0_rate_2_rel_nviews_2/checkpoints/last.ckpt  

    model_config:
      type: basic
      base_learning_rate: 1e-4
      d_out: 128
      n_hidden: 5
      d_hidden: 128
      action_space:
        pos:
          type: "continuous"
          size: 3
          min: -1.0
          max: 1.0
        quat:
          type: "continuous"
          size: 4
          min: -2.1
          max: 2.1
        close:
          type: "discrete"
          size: 2
          min: -1.0
 
    backbone_config:
          backbone: basic2
          type: global
          encode_cam: false
          frame_stack: 3
          layer_norm: true
    augment: true
    discrete_loss_weight: 1e-6
    pad: 2

data:
  target: main.DataModuleFromConfig
  params:

    batch_size: 128
    num_workers: 1
    wrap: True
    train:
      target: src.data.RealWorldDataset.TeleopData
      params:
        directory: /work/dlclarge2/faridk-nerf_il/data/expert_data/train #/work/dlclarge2/faridk-nerf_rl/old/srn_block_insertion/block_insertion
        frame_stack: 3
        relative: true
        frame_rate: 3
        views:

          - 1
          - 2
          - 0

        #  - 1

    validation:
      target: src.data.RealWorldDataset.TeleopData
      params:
        directory: /work/dlclarge2/faridk-nerf_il/data/expert_data/val #/work/dlclarge2/faridk-nerf_rl/old/srn_block_insertion/block_insertion
        frame_stack: 3
        frame_rate: 3
        relative: true
        views:
          - 1
          - 2
          - 0
          

        #  - 1

    test:
      target: src.data.RealWorldDataset.TeleopData
      params:
        directory: /work/dlclarge2/faridk-nerf_il/data/expert_data/val #/work/dlclarge2/faridk-nerf_rl/old/srn_block_insertion/block_insertion
        frame_stack: 3
        frame_rate: 3
        relative: true
        views:
          - 1
          - 2
          - 0

        #  - 1



lightning:
  logger:
    params:
      entity: kifarid
      project: Nerf_for_control

  trainer:
    benchmark: True
    log_every_n_steps: 10 #10
    accumulate_grad_batches: 1
    devices: 0,
    accelerator: "gpu"
    #limit_train_batches: 2 #remove
    #limit_val_batches: 1 #10
    #limit_test_batches: 0 #10
    max_epochs: 10000