data:
  format: ravens
  views_per_scene: 3
  datadir: /work/dlclarge2/faridk-nerf_rl/old/srn_block_insertion/block_insertion
renderer: 
  white_bkgd: false
  no_bbox_step: 0
  gpus:
#train: 
  #wandb: true
  #project: Nerf_for_control
  #entity: kifarid