config: 
  sn64: conf/exp/sn64.conf
  sn64_unseen: conf/exp/sn64_unseen.conf
  srn_chair: conf/exp/srn.conf
  srn_car: conf/exp/srn.conf
  dtu: conf/exp/dtu.conf
  multi_obj: conf/exp/multi_obj.conf
datadir: 