config:
  sn64: configs/exp/sn64.yaml
  sn64_unseen: configs/exp/sn64_unseen.yaml
  srn_chair: configs/exp/srn.yaml
  srn_car: configs/exp/srn.yaml
  dtu: configs/exp/dtu.yaml
  multi_obj: configs/exp/multi_obj.yaml
  ravens: configs/exp/ravens.yaml
datadir: 